name: tr_store_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #comparing dart objects
  equatable: ^2.0.5

  #make request to api
  retrofit: ^3.0.1

  #Database
  floor: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  floor_generator: ^1.2.0
  build_runner: ^2.4.8
  retrofit_generator: ^4.2.0

flutter:
  uses-material-design: true